### ISSUE TITLE
In GitHub Actions slackdump fails to load credentials

### ISSUE THREAD

**Issue by iainelder** [rusq/slackdump#404]
**Describe the bug**

I'm trying to run slackdump in GitHub Actions (GHA) so that I may have scheduled backups.

My workflow suceeds in Nektos Act, but fails in the real GHA.

In GHA it fails to load the credentials file. Exactly the same file works on Nektos Act.

**To Reproduce**

In an AWS account:

* Create the CloudFormation stack for the GitHub Actions IAM role
* Create an S3 bucket for sessions (use the console)
* Create an S3 bucket for backups (use the console)

In a GitHub repo:

* Configure the workflow (put real values for any placeholders)
* Configure the supporting files (or merge them inline to the workflow) (put real values for any placeholders)

GitHub Actions: Dispatch the workflow.

Nektos Act: run `./test-workflow.sh` (See additional context below)

**Expected behavior**

nektos act shows this output for workspace ABC. It loads the saved credentials and proceed to complete the dump.

```
| + slackdump export -workspace ABC -member-only -o ABC_export_2025-01-11_2025-01-12.zip -time-from 2025-01-11T00:00:00 -time-to 2025-01-12T00:00:00 -v
| 2025/01/12 13:32:35 DEBUG loaded saved credentials cache_dir=/home/runner/.cache/slackdump filename=ABC.bin workspace=ABC
```

**Output**

In the real GHA, the workflow fails to load the saved credentials.

It says there is an "invalid character". The offending character may vary according to the content of the credentials file.

Then it prints some junk: `25l2004h1004h`. I think this is something to do with the faketty function, but I'm not sure.

After the junk output, the workflow stops printing. It hangs until I cancel the execution.

```
+ slackdump export -workspace ABC -member-only -o ABC_export_2025-01-11_2025-01-12.zip -time-from 2025-01-11T00:00:00 -time-to 2025-01-12T00:00:00 -v
2025/01/12 13:36:17 DEBUG failed to load saved credentials: invalid character ')' looking for beginning of value
25l2004h1004h
```

**Desktop (please complete the following information):**

 - Desktop OS version: Ubuntu 24.04.1 LTS
 - Slackdump version: 3.0.2
 - Nektos Act version: 0.2.71
 - GitHub Actions version:
 
   ```
   Current runner version: '2.321.0'
   Operating System
    Ubuntu
    22.04.5
    LTS
   Runner Image
    Image: ubuntu-22.04
    Version: 20250105.1.0
    Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20250105.1/images/ubuntu/Ubuntu2204-Readme.md
    Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20250105.1
   Runner Image Provisioner
    2.0.404.1
   ```

**Additional context**

Placeholder values:

* `<AWS_ACCOUNT_ID>`
* `<BACKUP_BUCKET_NAME>`
* `<SESSION_BUCKET_NAME>`

GitHub Actions workflow:

```yaml
---
on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:

      - name: Install slackdump
        uses: giantswarm/install-binary-action@v3
        with:
          binary: slackdump
          version: 3.0.2
          download_url: https://github.com/rusq/slackdump/releases/download/v${version}/slackdump_Linux_x86_64.tar.gz
          tarball_binary_path: ${binary}
          smoke_test: "${binary} version"

      - name: Get AWS session
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/GitHubActionsRole-Role-5W9RPYJYRPZN

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get Slack session
        run: ./get-slack-session.sh

      - name: Set date range
        id: date-range
        run: |
          yesterday=$(date --utc --iso=date  --date "$today - 1 day")
          today=$(date --utc --iso=date)
          echo "end=$today" >> "$GITHUB_OUTPUT"
          echo "start=$yesterday" >> "$GITHUB_OUTPUT"

      - name: Backup
        run: |
          start="${{ steps.date-range.outputs.start }}"
          end="${{ steps.date-range.outputs.end }}"

          faketty () {
            script -qefc "$(printf "%q " "$@")" /dev/null
          }

          faketty ./backup.sh <WORKSPACE_NAME> $start $end

permissions: write-all
```

backup.sh

```bash
#!/bin/bash

set -euxo pipefail

workspace="$1"

from_date=$(date --iso=date --utc --date "${2:-"today -1 day"}")
to_date=$(date --iso=date --utc --date "${3:-"today"}")
export_filename="${workspace}_export_${from_date}_${to_date}.zip"

ls -l ~/.cache/slackdump

slackdump export \
  -workspace "$workspace" \
  -member-only \
  -o "$export_filename" \
  -time-from "${from_date}T00:00:00" \
  -time-to "${to_date}T00:00:00" \
  -v

aws s3 cp "$export_filename" s3://<BACKUP_BUCKET_NAME>
```

get-slack-session.sh

```bash
aws s3 sync s3://<SLACK_SESSIONS_BUCKET>/ ~/.cache/slackdump/

ls -l ~/.cache/slackdump
```

test-workflow.sh

```
act workflow_dispatch --env-file <(aws configure export-credentials --format env)
```

CloudFormation template for GitHubActionsRole:

```yaml
Parameters:
  GitHubOrg:
    Description: Name of GitHub organization/user (case sensitive)
    Type: String
  RepositoryName:
    Description: Name of GitHub repository (case sensitive)
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider. (optional)
    Default: ""
    Type: String
  OIDCAudience:
    Description: Audience supplied to configure-aws-credentials.
    Default: "sts.amazonaws.com"
    Type: String
  AllowAccountToAssumeRole:
    Description: |
      GitHub Actions may assume the role. When AllowAccountToAssumeRole is
      true, then any role in the account may assume the role too.
    Default: "true"
    Type: String

Conditions:
  CreateOIDCProvider: !Equals
    - !Ref OIDCProviderArn
    - ""

  AllowAccountToAssumeRole: !Equals
    - !Ref AllowAccountToAssumeRole
    - "true"


Resources:

  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !Ref GithubOidc
                - !Ref OIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*

          - !If
            - AllowAccountToAssumeRole
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - sts:TagSession
              Principal:
                AWS: !Ref AWS::AccountId
            - !Ref AWS::NoValue

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff

Outputs:
  Role:
    Value: !GetAtt Role.Arn
```
